on: [push]

jobs:
  tests:
    name: All Tests
    timeout-minutes: 10
    runs-on: macos-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Download and start iTerm2
        run: |
          tmp_zip=$(mktemp -u iterm.zip.XXXXXXX)
          curl https://iterm2.com/downloads/beta/iTerm2-3_4_2beta3.zip > "$tmp_zip"
          unzip "$tmp_zip"
          mv iTerm.app /Applications/iTerm.app

      - name: Run tests
        run: |
          ITERMCTL_LOG_LEVEL=fatal make integration_test
